### ISSUE TITLE
lock DB directory: open /data/lock: permission denied

### ISSUE THREAD

**Issue by gecube** [coroot/coroot#380]
Reported originally by @bigmacman telegram user.

Steps to reproduce:

1. take hetzner ubuntu on arm 
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble
```
2. install docker + docker compose
```bash
$ docker version
Client:
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.22.2
 Git commit:        24.0.7-0ubuntu4.1
 Built:             Fri Aug  9 02:33:20 2024
 OS/Arch:           linux/arm64
 Context:           default

Server:
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.22.2
  Git commit:       24.0.7-0ubuntu4.1
  Built:            Fri Aug  9 02:33:20 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.12
  GitCommit:        
 runc:
  Version:          1.1.12-0ubuntu3.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        
```

```bash
$ docker-compose version
Docker Compose version v2.30.3
```

```bash
$ curl -fsS https://raw.githubusercontent.com/coroot/coroot/main/deploy/docker-compose.yaml | docker-compose -f - up -d
```

3. getting the next:

```bash
$ docker ps
CONTAINER ID   IMAGE                                 COMMAND                  CREATED         STATUS                          PORTS                                          NAMES
5f498b7b1e24   ghcr.io/coroot/coroot-cluster-agent   "coroot-cluster-agen…"   4 minutes ago   Restarting (1) 44 seconds ago                                                  coroot-cluster-agent-1
118d3c4652bc   ghcr.io/coroot/coroot                 "/opt/coroot/coroot …"   4 minutes ago   Up 4 minutes                    0.0.0.0:8080->8080/tcp, :::8080->8080/tcp      coroot-coroot-1
8346a6a6f176   prom/prometheus:v2.45.4               "/bin/prometheus --c…"   4 minutes ago   Up 4 minutes                    127.0.0.1:9090->9090/tcp                       coroot-prometheus-1
279ca85363c7   ghcr.io/coroot/coroot-node-agent      "coroot-node-agent -…"   4 minutes ago   Up 4 minutes                                                                   coroot-node-agent-1
9c540bcc785d   clickhouse/clickhouse-server:24.3     "/entrypoint.sh"         4 minutes ago   Up 4 minutes                    8123/tcp, 9009/tcp, 127.0.0.1:9000->9000/tcp   coroot-clickhouse-1
```

the cluster agent is restarting permanently. 

```bash
$ docker logs coroot-cluster-agent-1
I1113 13:46:52.560555       1 main.go:22] version: 1.1.1
I1113 13:46:52.561279       1 config.go:36] endpoint: http://coroot:8080/v1/config, update interval: 1m0s
I1113 13:46:52.561797       1 metrics.go:59] endpoint: http://coroot:8080/v1/metrics, scrape interval: 15s
I1113 13:46:52.563140       1 prom.go:217] level info remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg Starting WAL watcher queue 0a4aa4
I1113 13:46:52.566870       1 prom.go:217] level error remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg error tailing WAL err wal.Segments: open /data/wal: no such file or directory
F1113 13:46:52.570101       1 main.go:42] lock DB directory: open /data/lock: permission denied
I1113 13:46:53.086110       1 main.go:22] version: 1.1.1
I1113 13:46:53.086377       1 config.go:36] endpoint: http://coroot:8080/v1/config, update interval: 1m0s
I1113 13:46:53.086585       1 metrics.go:59] endpoint: http://coroot:8080/v1/metrics, scrape interval: 15s
I1113 13:46:53.090556       1 prom.go:217] level info remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg Starting WAL watcher queue 0a4aa4
I1113 13:46:53.091963       1 prom.go:217] level error remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg error tailing WAL err wal.Segments: open /data/wal: no such file or directory
F1113 13:46:53.093270       1 main.go:42] lock DB directory: open /data/lock: permission denied
I1113 13:46:53.623331       1 main.go:22] version: 1.1.1
I1113 13:46:53.623718       1 config.go:36] endpoint: http://coroot:8080/v1/config, update interval: 1m0s
I1113 13:46:53.623891       1 metrics.go:59] endpoint: http://coroot:8080/v1/metrics, scrape interval: 15s
I1113 13:46:53.624785       1 prom.go:217] level info remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg Starting WAL watcher queue 0a4aa4
I1113 13:46:53.625143       1 prom.go:217] level error remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg error tailing WAL err wal.Segments: open /data/wal: no such file or directory
F1113 13:46:53.625883       1 main.go:42] lock DB directory: open /data/lock: permission denied
I1113 13:46:54.347981       1 main.go:22] version: 1.1.1
I1113 13:46:54.348611       1 config.go:36] endpoint: http://coroot:8080/v1/config, update interval: 1m0s
I1113 13:46:54.348755       1 metrics.go:59] endpoint: http://coroot:8080/v1/metrics, scrape interval: 15s
I1113 13:46:54.349499       1 prom.go:217] level info remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg Starting WAL watcher queue 0a4aa4
I1113 13:46:54.350275       1 prom.go:217] level error remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg error tailing WAL err wal.Segments: open /data/wal: no such file or directory
F1113 13:46:54.350777       1 main.go:42] lock DB directory: open /data/lock: permission denied
I1113 13:46:55.478172       1 main.go:22] version: 1.1.1
I1113 13:46:55.478504       1 config.go:36] endpoint: http://coroot:8080/v1/config, update interval: 1m0s
I1113 13:46:55.478681       1 metrics.go:59] endpoint: http://coroot:8080/v1/metrics, scrape interval: 15s
I1113 13:46:55.479300       1 prom.go:217] level info remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg Starting WAL watcher queue 0a4aa4
I1113 13:46:55.480047       1 prom.go:217] level error remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg error tailing WAL err wal.Segments: open /data/wal: no such file or directory
F1113 13:46:55.480628       1 main.go:42] lock DB directory: open /data/lock: permission denied
I1113 13:46:57.377631       1 main.go:22] version: 1.1.1
I1113 13:46:57.377800       1 config.go:36] endpoint: http://coroot:8080/v1/config, update interval: 1m0s
I1113 13:46:57.377836       1 metrics.go:59] endpoint: http://coroot:8080/v1/metrics, scrape interval: 15s
I1113 13:46:57.378432       1 prom.go:217] level info remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg Starting WAL watcher queue 0a4aa4
F1113 13:46:57.380750       1 main.go:42] lock DB directory: open /data/lock: permission denied
I1113 13:47:00.828621       1 main.go:22] version: 1.1.1
I1113 13:47:00.828776       1 config.go:36] endpoint: http://coroot:8080/v1/config, update interval: 1m0s
I1113 13:47:00.828812       1 metrics.go:59] endpoint: http://coroot:8080/v1/metrics, scrape interval: 15s
I1113 13:47:00.829274       1 prom.go:217] level info remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg Starting WAL watcher queue 0a4aa4
I1113 13:47:00.829836       1 prom.go:217] level error remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg error tailing WAL err wal.Segments: open /data/wal: no such file or directory
F1113 13:47:00.831220       1 main.go:42] lock DB directory: open /data/lock: permission denied
I1113 13:47:07.524368       1 main.go:22] version: 1.1.1
I1113 13:47:07.524567       1 config.go:36] endpoint: http://coroot:8080/v1/config, update interval: 1m0s
I1113 13:47:07.524771       1 metrics.go:59] endpoint: http://coroot:8080/v1/metrics, scrape interval: 15s
I1113 13:47:07.525616       1 prom.go:217] level info remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg Starting WAL watcher queue 0a4aa4
I1113 13:47:07.525941       1 prom.go:217] level error remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg error tailing WAL err wal.Segments: open /data/wal: no such file or directory
F1113 13:47:07.526844       1 main.go:42] lock DB directory: open /data/lock: permission denied
I1113 13:47:20.606275       1 main.go:22] version: 1.1.1
I1113 13:47:20.606607       1 config.go:36] endpoint: http://coroot:8080/v1/config, update interval: 1m0s
I1113 13:47:20.606728       1 metrics.go:59] endpoint: http://coroot:8080/v1/metrics, scrape interval: 15s
I1113 13:47:20.607224       1 prom.go:217] level info remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg Starting WAL watcher queue 0a4aa4
F1113 13:47:20.607850       1 main.go:42] lock DB directory: open /data/lock: permission denied
I1113 13:47:46.492486       1 main.go:22] version: 1.1.1
I1113 13:47:46.492826       1 config.go:36] endpoint: http://coroot:8080/v1/config, update interval: 1m0s
I1113 13:47:46.492989       1 metrics.go:59] endpoint: http://coroot:8080/v1/metrics, scrape interval: 15s
I1113 13:47:46.493555       1 prom.go:217] level info remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg Starting WAL watcher queue 0a4aa4
I1113 13:47:46.494261       1 prom.go:217] level error remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg error tailing WAL err wal.Segments: open /data/wal: no such file or directory
F1113 13:47:46.495378       1 main.go:42] lock DB directory: open /data/lock: permission denied
I1113 13:48:38.001720       1 main.go:22] version: 1.1.1
I1113 13:48:38.002346       1 config.go:36] endpoint: http://coroot:8080/v1/config, update interval: 1m0s
I1113 13:48:38.002657       1 metrics.go:59] endpoint: http://coroot:8080/v1/metrics, scrape interval: 15s
I1113 13:48:38.003661       1 prom.go:217] level info remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg Starting WAL watcher queue 0a4aa4
I1113 13:48:38.004621       1 prom.go:217] level error remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg error tailing WAL err wal.Segments: open /data/wal: no such file or directory
F1113 13:48:38.005941       1 main.go:42] lock DB directory: open /data/lock: permission denied
I1113 13:49:38.286938       1 main.go:22] version: 1.1.1
I1113 13:49:38.287435       1 config.go:36] endpoint: http://coroot:8080/v1/config, update interval: 1m0s
I1113 13:49:38.287713       1 metrics.go:59] endpoint: http://coroot:8080/v1/metrics, scrape interval: 15s
I1113 13:49:38.289100       1 prom.go:217] level info remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg Starting WAL watcher queue 0a4aa4
I1113 13:49:38.289263       1 prom.go:217] level error remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg error tailing WAL err wal.Segments: open /data/wal: no such file or directory
F1113 13:49:38.289850       1 main.go:42] lock DB directory: open /data/lock: permission denied
I1113 13:50:38.544676       1 main.go:22] version: 1.1.1
I1113 13:50:38.544846       1 config.go:36] endpoint: http://coroot:8080/v1/config, update interval: 1m0s
I1113 13:50:38.544897       1 metrics.go:59] endpoint: http://coroot:8080/v1/metrics, scrape interval: 15s
I1113 13:50:38.545370       1 prom.go:217] level info remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg Starting WAL watcher queue 0a4aa4
F1113 13:50:38.545979       1 main.go:42] lock DB directory: open /data/lock: permission denied
I1113 13:51:38.802562       1 main.go:22] version: 1.1.1
I1113 13:51:38.802755       1 config.go:36] endpoint: http://coroot:8080/v1/config, update interval: 1m0s
I1113 13:51:38.802805       1 metrics.go:59] endpoint: http://coroot:8080/v1/metrics, scrape interval: 15s
I1113 13:51:38.803368       1 prom.go:217] level info remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg Starting WAL watcher queue 0a4aa4
I1113 13:51:38.803700       1 prom.go:217] level error remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg error tailing WAL err wal.Segments: open /data/wal: no such file or directory
F1113 13:51:38.804194       1 main.go:42] lock DB directory: open /data/lock: permission denied
```

**Comment by gecube** [comment]
Changed to `ghcr.io/coroot/coroot-cluster-agent:1.1.0`

Still successful run:

```bash
$ docker ps
CONTAINER ID   IMAGE                                       COMMAND                  CREATED          STATUS          PORTS                                          NAMES
bd14cea22ed1   ghcr.io/coroot/coroot-cluster-agent:1.1.0   "coroot-cluster-agen…"   16 seconds ago   Up 14 seconds                                                  coroot-cluster-agent-1
e77ef8086ac2   ghcr.io/coroot/coroot                       "/opt/coroot/coroot …"   16 seconds ago   Up 15 seconds   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp      coroot-coroot-1
a28298ab845f   clickhouse/clickhouse-server:24.3           "/entrypoint.sh"         16 seconds ago   Up 15 seconds   8123/tcp, 9009/tcp, 127.0.0.1:9000->9000/tcp   coroot-clickhouse-1
db2f7b3d9603   prom/prometheus:v2.45.4                     "/bin/prometheus --c…"   16 seconds ago   Up 15 seconds   127.0.0.1:9090->9090/tcp                       coroot-prometheus-1
a9dec7eb8c50   ghcr.io/coroot/coroot-node-agent            "coroot-node-agent -…"   16 seconds ago   Up 15 seconds                                                  coroot-node-agent-1
0bb8c6b78a30   netbirdio/netbird:latest                    "/usr/local/bin/netb…"   7 weeks ago      Up 7 weeks 
```

**Comment by gecube** [comment]
changed to `ghcr.io/coroot/coroot-cluster-agent:1.1.1` and the issue was reproduced:

```bash
$ docker ps
CONTAINER ID   IMAGE                                       COMMAND                  CREATED         STATUS                                  PORTS                                          NAMES
6f60a2c098f8   ghcr.io/coroot/coroot-cluster-agent:1.1.1   "coroot-cluster-agen…"   3 seconds ago   Restarting (1) Less than a second ago                                                  coroot-cluster-agent-1
ed0ae2c0bca7   ghcr.io/coroot/coroot                       "/opt/coroot/coroot …"   3 seconds ago   Up 1 second                             0.0.0.0:8080->8080/tcp, :::8080->8080/tcp      coroot-coroot-1
f8326cb58e29   ghcr.io/coroot/coroot-node-agent            "coroot-node-agent -…"   3 seconds ago   Up 2 seconds                                                                           coroot-node-agent-1
93b2b3ee9f73   clickhouse/clickhouse-server:24.3           "/entrypoint.sh"         3 seconds ago   Up 1 second                             8123/tcp, 9009/tcp, 127.0.0.1:9000->9000/tcp   coroot-clickhouse-1
b55359bd7839   prom/prometheus:v2.45.4                     "/bin/prometheus --c…"   3 seconds ago   Up 2 seconds                            127.0.0.1:9090->9090/tcp                       coroot-prometheus-1
```

**Comment by apetruhin** [comment]
@gecube, thanks for the report. Fixed in the latest cluster-agent version ([1.1.2](https://github.com/coroot/coroot-cluster-agent/releases/tag/v1.1.2)).

You can upgrade by rerunning ```curl ... | docker-compose up ...```.

**Comment by gh0st3e** [comment]
Still have this problem on 1.1.2

`I1217 07:50:04.696038       1 main.go:22] version: 1.1.2
I1217 07:50:04.696135       1 config.go:36] endpoint: http://coroot:8080/v1/config, update interval: 1m0s
I1217 07:50:04.696170       1 metrics.go:59] endpoint: http://coroot:8080/v1/metrics, scrape interval: 15s
I1217 07:50:04.696696       1 prom.go:217] level info remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg Starting WAL watcher queue 0a4aa4
I1217 07:50:04.697139       1 prom.go:217] level info remote_name 0a4aa4 url http://coroot:8080/v1/metrics msg Replaying WAL queue 0a4aa4
I1217 07:50:04.697397       1 prom.go:217] level warn msg A lockfile from a previous execution already existed. It was replaced file /data/lock
F1217 07:50:04.697429       1 main.go:42] lock DB directory: open /data/lock: permission denied`

**Comment by apetruhin** [comment]
@gh0st3e,
Upgrading from versions prior to 1.1.0 seems to fail.
As a workaround, I suggest removing the volume (it only contains a temporary metrics WAL, so nothing important is lost).
```
docker rm -f coroot-cluster-agent-1
docker volume rm coroot_cluster_agent_data
curl -fsS https://raw.githubusercontent.com/coroot/coroot/main/deploy/docker-compose.yaml | docker compose -f - up -d
```
